---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: infisical.vault
    version: 1.2.1
  - name: grafana.grafana
    version: 6.0.6
  - name: community.proxmox
    version: 1.5.0
  - name: oxlorg.opnsense
    version: 25.7.8
